### ISSUE TITLE
Found a bug in exception loop

### ISSUE THREAD

**Issue by TakumiHaruta** [aws-samples/aws-security-hub-cross-account-controls-disabler#6]
@ahmedqe 
Hi, this sample code helped a lot to set up Security Hub in our AWS environment. Thank you so much.
I found a bug in the `UpdateMember/index.py`, so let me explain.

There are `admin_control` and `member_control` generated by `zip(admin_controls[admin_key], member_controls[member_key])` at iine 159, but items in `admin_controls[admin_key]` and `member_controls[member_key]` are not always in the same order.

https://github.com/aws-samples/aws-security-hub-cross-account-controls-disabler/blob/main/UpdateMembers/src/UpdateMember/index.py#L159

In this case, `itertools.product()` is supposed to be used instead of `zip()` to combine all cases, and add a condition to compare `admin_control["ControlId"]` with `member_control["ControlId"]` to move on to the following process.

```py
    for admin_key in admin_controls:
        for member_key in member_controls:
            if admin_key == member_key:
                # Same security standard TODO
                for admin_control, member_control in itertools.product(
                    admin_controls[admin_key], member_controls[member_key]
                ):
                    if admin_control["ControlId"] == member_control["ControlId"]:
                        # Check for exceptions first
                        if admin_control["ControlId"] in exceptions["Disabled"]:
                            if member_control["ControlStatus"] != DISABLED:
                                # Disable control in member account
                                update_control_status(
                                    member_control,
                                    member_security_hub_client,
                                    DISABLED,
                                    disabled_reason=exceptions["DisabledReason"][
                                        admin_control["ControlId"]
                                    ],
                                )
```

**Comment by AlexeyMihalich** [comment]
Hey, 
Please review the change, because this affected all the controls in the member accounts, and not just the control that you want to disable.
Meaning that if you change something in the master account, this change affects **all of the controls** in the member accounts.
After switching back to zip(), its working as expected.

**Comment by ahmedqe** [comment]
That is not a bug. The suggestion does not work either.
