### ISSUE TITLE
Checks no longer disabling

### ISSUE THREAD

**Issue by rosswickman** [aws-samples/aws-security-hub-cross-account-controls-disabler#7]
I have deployed this solution multiple times but I am getting a strange result.
I am not sure if it is related to the release of CIS v1.4 or something else.
The Disabled 'Reason', As well as control status, updates to 'disabled' in each child account as expected. However, the total score and disabled check count are not reflected as true with the disabled checks.
![CleanShot 2022-12-12 at 14 11 37](https://user-images.githubusercontent.com/1621528/207145114-e1422d9f-859d-438e-ac96-eee5bd1196cc.png)
![CleanShot 2022-12-12 at 14 13 08](https://user-images.githubusercontent.com/1621528/207145149-22b5f808-9e68-48bc-bb38-146ccc2813ba.png)

**Comment by sopel** [comment]
@rosswickman - surprisingly it can take up to 24 hours to update the score and counts, it's even emphasized when disabling controls manually via the UI:

![image](https://user-images.githubusercontent.com/545193/228814122-4cf04c7d-3040-477b-b84e-d5233fc0b84e.png)

The disabling as such works regardless though, i.e. the expected state of the control as observed in the UI is accurate and will be reflected in the score and counts after 24 hours the latest.

**Comment by rosswickman** [comment]
The issue here was actually that the aggregated region did not also have the checks disabled. 
Once I disabled the whole standard or the individual checks then the numbers updated correctly. 
I'm unsure how this will perform now with consolidated checks.
