### ISSUE TITLE
get member function includes disabled AWS accounts

### ISSUE THREAD

**Issue by tbugfinder** [aws-samples/aws-security-hub-cross-account-controls-disabler#8]
The get_member function should skip disabled AWS accounts as those are no longer available.

https://github.com/aws-samples/aws-security-hub-cross-account-controls-disabler/blob/fd04bd2780a96e53cb350a5812db62f4ab0c2371/UpdateMembers/src/GetMembers/index.py#L102-L103

**Comment by ahmedqe** [comment]
fixed!
